INSERT INTO USERS
VALUES (1, 'a@a.com', 'admin', '$2a$10$17JJjJ/cJx6MX.4oyI0JSu862tPxHCTPgg/DHsI3YBLTIkZpn7Che', 'ADMIN');
INSERT INTO USERS
VALUES (2, 'b@b.com', 'operator', '$2a$10$17JJjJ/cJx6MX.4oyI0JSu862tPxHCTPgg/DHsI3YBLTIkZpn7Che', 'ADOPS');
INSERT INTO USERS
VALUES (3, 'c@c.com', 'publisher1', '$2a$10$17JJjJ/cJx6MX.4oyI0JSu862tPxHCTPgg/DHsI3YBLTIkZpn7Che', 'PUBLISHER');
INSERT INTO USERS
VALUES (4, 'x@x.com', 'publisher2', '$2a$10$17JJjJ/cJx6MX.4oyI0JSu862tPxHCTPgg/DHsI3YBLTIkZpn7Che', 'PUBLISHER');

INSERT INTO APPS
VALUES (1, 'app1', 'IOS', 3);
INSERT INTO APPS
VALUES (2, 'app2', 'ANDROID', 3);
INSERT INTO APPS
VALUES (3, 'app3', 'WEBSITE', 3);
INSERT INTO APPS
VALUES (4, 'app4', 'IOS', 4);

INSERT INTO APP_CONTENT_TYPES
VALUES (1, 'VIDEO');
INSERT INTO APP_CONTENT_TYPES
VALUES (2, 'VIDEO');
INSERT INTO APP_CONTENT_TYPES
VALUES (2, 'IMAGE');
INSERT INTO APP_CONTENT_TYPES
VALUES (3, 'VIDEO');
INSERT INTO APP_CONTENT_TYPES
VALUES (3, 'IMAGE');
INSERT INTO APP_CONTENT_TYPES
VALUES (3, 'HTML');
INSERT INTO APP_CONTENT_TYPES
VALUES (4, 'VIDEO');