INSERT INTO USERS
VALUES (1, 'a@a.com', 'admin', '$2y$12$H/FUN96InArZnmu3Gvwq4etHt6siMPKlXIBRtASVGtoWiShw6aQfS', 'ADMIN');
INSERT INTO USERS
VALUES (2, 'b@b.com', 'operator', '$2y$12$H/FUN96InArZnmu3Gvwq4etHt6siMPKlXIBRtASVGtoWiShw6aQfS', 'ADOPS');
INSERT INTO USERS
VALUES (3, 'c@c.com', 'publisher', '$2y$12$H/FUN96InArZnmu3Gvwq4etHt6siMPKlXIBRtASVGtoWiShw6aQfS', 'PUBLISHER');

INSERT INTO APPS
VALUES (1, 'app1', 'IOS', 3);
INSERT INTO APPS
VALUES (2, 'app2', 'ANDROID', 3);
INSERT INTO APPS
VALUES (3, 'app3', 'WEBSITE', 3);

INSERT INTO APP_CONTENT_TYPES
VALUES (1, 'VIDEO');
INSERT INTO APP_CONTENT_TYPES
VALUES (2, 'VIDEO');
INSERT INTO APP_CONTENT_TYPES
VALUES (2, 'IMAGE');
INSERT INTO APP_CONTENT_TYPES
VALUES (3, 'VIDEO');
INSERT INTO APP_CONTENT_TYPES
VALUES (3, 'IMAGE');
INSERT INTO APP_CONTENT_TYPES
VALUES (3, 'HTML');